name: Tagged Release Distribution

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  all_jobs:
    name: Tests, Builds, Coverage, Release Uploads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies (npm ci)
        run: npm ci --no-fund
      - name: Run Tests
        run: npm run test -- --verbose
      - name: Run Lint
        run: npm run lint
      - name: Ensure Version is Updated
        run: node ./tools/replaceVersionNumber.js
      - name: Run Build
        id: runbuild
        run: |
          npm run build
          node ./tools/generateManifest.js firefox builds/firefox-manifest.json
          echo "ffxpi=$(ls builds/*Firefox.xpi)" >> "$GITHUB_OUTPUT"
      - name: Archive Production Build Artifacts
        if: success()
        uses: actions/upload-artifact@v7
        with:
          name: builds
          path: builds
      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage
      - name: GitHub Releases
        id: github_releases
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            builds/Cookie-AutoDelete_*_Chrome.zip
            builds/Cookie-AutoDelete_*_Firefox.xpi
          body: This is an auto-generated tagged release - Change log will be manually inserted soon! Latest versions have been submitted to the relevant browser extension store for review.
          prerelease: ${{ endsWith(github.ref, 'alpha') || endsWith(github.ref, 'beta') }}
          draft: true
      - name: Google Chrome WebStore Upload
        uses: Passiverecords/chrome-extension-upload-action@d46910ee6515270bde08c1fe2bf0bceaaf5d7fb7 # 1.4.1
        if: startsWith(github.ref, 'refs/tags/') && !(endsWith(github.ref, 'alpha') || endsWith(github.ref, 'beta'))
        with:
          app-id: 'fhcgjolkccmbidfldomjliifgaodjagh'
          file-name: 'builds/Cookie-AutoDelete_*_Chrome.zip'
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false
      - name: Mozilla Firefox AMO Upload
        uses: trmcnvn/firefox-addon@0d05671269b82c69c3f22ed86d8e772e89d47cf4 # v1
        if: startsWith(github.ref, 'refs/tags/') && !(endsWith(github.ref, 'alpha') || endsWith(github.ref, 'beta'))
        with:
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
          uuid: 'CookieAutoDelete@kennydo.com'
          xpi: ${{ steps.runbuild.outputs.ffxpi }}
          manifest: builds/firefox-manifest.json
